# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )
Rails.application.config.assets.precompile += %w( buttons_saad.css )
Rails.application.config.assets.precompile += %w( informations.js )
Rails.application.config.assets.precompile += %w( bootbox.css )
Rails.application.config.assets.precompile += %w( curriculo.js )
Rails.application.config.assets.precompile += %w( bootstrap.min.css )
Rails.application.config.assets.precompile += %w( font-awesome.min.css )
Rails.application.config.assets.precompile += %w( devicons.min.css )
Rails.application.config.assets.precompile += %w( simple-line-icons.css )
Rails.application.config.assets.precompile += %w( resume.min.css )
Rails.application.config.assets.precompile += %w( bootstrap.bundle.min.js )
Rails.application.config.assets.precompile += %w( jquery.easing.min.js )
Rails.application.config.assets.precompile += %w( resume.min.js )
Rails.application.config.assets.precompile += %w( testando.js )
Rails.application.config.assets.precompile += %w( quiz.js )
Rails.application.config.assets.precompile += %w( quizzes.js )
Rails.application.config.assets.precompile += %w( question_socio_emotinal.js )
Rails.application.config.assets.precompile += %w( question_socio_emotinals.js )
Rails.application.config.assets.precompile += %w( growl.js )
Rails.application.config.assets.precompile += %w( results.js )
Rails.application.config.assets.precompile += %w( result_socio_emotionals.js )
Rails.application.config.assets.precompile += %w( registrations.js )
Rails.application.config.assets.precompile += %w( subjects.js )
Rails.application.config.assets.precompile += %w( admin.js )
Rails.application.config.assets.precompile += %w( administrators.js )
Rails.application.config.assets.precompile += %w( anchorinfos.js )
Rails.application.config.assets.precompile += %w( anchors.js )
Rails.application.config.assets.precompile += %w( campus.js )
Rails.application.config.assets.precompile += %w( centers.js )
Rails.application.config.assets.precompile += %w( classrooms.js )
Rails.application.config.assets.precompile += %w( coordinators.js )
Rails.application.config.assets.precompile += %w( courses.js )
Rails.application.config.assets.precompile += %w( institutions.js )
Rails.application.config.assets.precompile += %w( principals.js )
Rails.application.config.assets.precompile += %w( students.js )
Rails.application.config.assets.precompile += %w( teachers.js )
Rails.application.config.assets.precompile += %w( users.js )
Rails.application.config.assets.precompile += %w( welcome.js )
Rails.application.config.assets.precompile += %w( SocioEmotionalcreatePdf.js )
Rails.application.config.assets.precompile += %w( createPdf.js )
Rails.application.config.assets.precompile += %w( createCsv.js )
Rails.application.config.assets.precompile += %w( pdfmake.min.js )
Rails.application.config.assets.precompile += %w( vsf_fonts.js )
Rails.application.config.assets.precompile += %w( jspdf.min.js )
Rails.application.config.assets.precompile += %w( jspdf.plugin.text-align.js )
Rails.application.config.assets.precompile += %w( teachers_area.js )
Rails.application.config.assets.precompile += %w( add_obs.js )
Rails.application.config.assets.precompile += %w( learning_quizzes.js )
Rails.application.config.assets.precompile += %w( learning_results.js )
Rails.application.config.assets.precompile += %w( bootstrap.css )
Rails.application.config.assets.precompile += %w( font-awesome.css )
Rails.application.config.assets.precompile += %w( style.css )
Rails.application.config.assets.precompile += %w( style-responsive.css )
Rails.application.config.assets.precompile += %w( font-awesome.css )
Rails.application.config.assets.precompile += %w( zabuto_calendar )
Rails.application.config.assets.precompile += %w( jquery.gritter )
Rails.application.config.assets.precompile += %w( lineicons/style.css )
Rails.application.config.assets.precompile += %w( chart-master/Chart.js )
Rails.application.config.assets.precompile += %w( zabuto_calendar.css )
Rails.application.config.assets.precompile += %w( jquery.js )
Rails.application.config.assets.precompile += %w( jquery-1.8.3.js )
Rails.application.config.assets.precompile += %w( bootstrap.js )
Rails.application.config.assets.precompile += %w( jquery.dcjqaccordion.2.7.js )
Rails.application.config.assets.precompile += %w( jquery.scrollTo.min.js )
Rails.application.config.assets.precompile += %w( jquery.nicescroll.js )
Rails.application.config.assets.precompile += %w( jquery.sparkline.js )
Rails.application.config.assets.precompile += %w( common-scripts.js )
Rails.application.config.assets.precompile += %w( gritter/js/jquery.gritter.js )
Rails.application.config.assets.precompile += %w( gritter/js/gritter-conf.js )
Rails.application.config.assets.precompile += %w( table-responsive.css )
Rails.application.config.assets.precompile += %w( coordinators_area.js )
Rails.application.config.assets.precompile += %w( events.js )
Rails.application.config.assets.precompile += %w( jquery.min.js )
Rails.application.config.assets.precompile += %w( jquery-migrate-3.0.0.min.js )
Rails.application.config.assets.precompile += %w( jquery-migrate-1.4.1.min.js )
Rails.application.config.assets.precompile += %w( search_learning.js )
Rails.application.config.assets.precompile += %w( jquery-1.8.3.min.js )
Rails.application.config.assets.precompile += %w( validation_learning.js )
Rails.application.config.assets.precompile += %w( jquery.backstretch.min.js )
Rails.application.config.assets.precompile += %w( search_learning_admin.js )
Rails.application.config.assets.precompile += %w( plano_modal.js )
Rails.application.config.assets.precompile += %w( add_reference.js )
